
[package]
name = "shinosawa_system_kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
embedded-graphics = "0.8.1"
limine = "0.4.0"
profont = "0.7.0"
