[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
bindeps = true

[build]
target = "x86_64-shinosawa.json"

[alias]
disk_image = "run --target=x86_64-unknown-linux-gnu -p disk_image"