[package]
name = "shinosawa_system_kotono"
version = "0.1.0"
edition = "2024"

[dependencies]
shinosawa_system_sysface = { version = "0.1.0", path = "../sysface" }

[[bin]]
name = "kotono"
path = "src/main.rs"
test = false
bench = false
